### ISSUE TITLE
Controller: Remove use of p-queue and use servicebus instead

### ISSUE THREAD

**Issue by mitchell-liatrio** [liatrio/terraform-azure-github-runner#49]
``` [tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by mitchell-liatrio** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```

**Comment by mitchell-liatrio** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
